### ISSUE TITLE
14 - Afficher une phrase en fonction des résultats obtenus

### ISSUE THREAD

**Issue by LucasBoudereaux** [BuonOmo/webquiz#19]
La page de résultat d’un examen doit indiquer la note obtenue dans l’examen. Le 
message devrait dépendre de la note obtenue par l’utilisateur. Il y aura 4 types de 
messages selon 4 paliers de notes différentes : (0% à 25%), (25%
à 50%), (50% à 75%) 
et (75% à 100%).

**Comment by BuonOmo** [comment]
T’es mauvais Jack[, tu sais pas jouer]
Bof, pas terrible
Aller encore un peu..
Quand on veut, on peut !
